from __future__ import annotations


SCHEMAS: dict[str, dict[str, object]] = {
    "intent_route": {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schema",
            "resolved_route",
            "confidence",
            "reason",
            "project_mode",
            "discovery_target",
            "generalization_note",
            "completion_assessment",
            "next_options",
        ],
        "properties": {
            "schema": {"type": "string"},
            "resolved_route": {"type": "string"},
            "confidence": {"type": "number"},
            "reason": {"type": "string"},
            "project_mode": {"type": "string"},
            "discovery_target": {"type": "string"},
            "generalization_note": {"type": "string"},
            "completion_assessment": {
                "type": "object",
                "additionalProperties": False,
                "required": ["state", "weak_points"],
                "properties": {
                    "state": {"type": "string"},
                    "weak_points": {"type": "array", "items": {"type": "string"}},
                },
            },
            "next_options": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["id", "label", "description"],
                    "properties": {
                        "id": {"type": "string"},
                        "label": {"type": "string"},
                        "description": {"type": "string"},
                    },
                },
            },
        },
    },
    "project_name_candidates": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "candidates", "recommended"],
        "properties": {
            "schema": {"type": "string"},
            "recommended": {"type": "string"},
            "candidates": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["name", "meaning", "memory_hook", "rationale", "functional_link", "metaphor", "word_validation"],
                    "properties": {
                        "name": {"type": "string"},
                        "meaning": {"type": "string"},
                        "memory_hook": {"type": "string"},
                        "rationale": {"type": "string"},
                        "functional_link": {"type": "string"},
                        "metaphor": {"type": "string"},
                        "word_validation": {"type": "string"},
                    },
                },
            },
        },
    },
    "implementation_plan": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "summary", "phases", "files_to_touch", "tests", "risks", "requires_code_change_approval"],
        "properties": {
            "schema": {"type": "string"},
            "summary": {"type": "string"},
            "phases": {"type": "array", "items": {"type": "string"}},
            "files_to_touch": {"type": "array", "items": {"type": "string"}},
            "tests": {"type": "array", "items": {"type": "string"}},
            "risks": {"type": "array", "items": {"type": "string"}},
            "requires_code_change_approval": {"type": "boolean"},
        },
    },
    "conversation_workflow": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "source_summary", "generalized_project_type", "workflow_blueprint", "skill_or_workflow_draft", "safety_notes", "next_options"],
        "properties": {
            "schema": {"type": "string"},
            "source_summary": {"type": "string"},
            "generalized_project_type": {"type": "string"},
            "workflow_blueprint": {"type": "array", "items": {"type": "string"}},
            "skill_or_workflow_draft": {"type": "string"},
            "safety_notes": {"type": "array", "items": {"type": "string"}},
            "next_options": {"type": "array", "items": {"type": "string"}},
        },
    },
    "feishu_record_content": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "title", "markdown", "summary", "next_actions"],
        "properties": {
            "schema": {"type": "string"},
            "title": {"type": "string"},
            "markdown": {"type": "string"},
            "summary": {"type": "string"},
            "next_actions": {"type": "array", "items": {"type": "string"}},
        },
    },
    "feishu_docs_summary": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "summary", "setup_steps", "permissions", "risks", "source_refs"],
        "properties": {
            "schema": {"type": "string"},
            "summary": {"type": "string"},
            "setup_steps": {"type": "array", "items": {"type": "string"}},
            "permissions": {"type": "array", "items": {"type": "string"}},
            "risks": {"type": "array", "items": {"type": "string"}},
            "source_refs": {"type": "array", "items": {"type": "string"}},
        },
    },
    "task_block": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "goal", "constraints", "target_project", "success_criteria"],
        "properties": {
            "schema": {"type": "string"},
            "goal": {"type": "string"},
            "constraints": {"type": "array", "items": {"type": "string"}},
            "target_project": {"type": "string"},
            "success_criteria": {"type": "array", "items": {"type": "string"}},
        },
    },
    "research_plan": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "source_families", "queries", "coverage_gates", "stop_conditions"],
        "properties": {
            "schema": {"type": "string"},
            "source_families": {"type": "array", "items": {"type": "string"}},
            "queries": {"type": "array", "items": {"type": "string"}},
            "coverage_gates": {"type": "array", "items": {"type": "string"}},
            "stop_conditions": {"type": "array", "items": {"type": "string"}},
        },
    },
    "search_plan": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "round_no", "source_plan", "requires_online", "coverage_gates", "stop_conditions"],
        "properties": {
            "schema": {"type": "string"},
            "round_no": {"type": "number"},
            "source_plan": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["source", "priority", "queries", "reason"],
                    "properties": {
                        "source": {"type": "string"},
                        "priority": {"type": "string"},
                        "queries": {"type": "array", "items": {"type": "string"}},
                        "reason": {"type": "string"},
                    },
                },
            },
            "requires_online": {"type": "boolean"},
            "coverage_gates": {"type": "array", "items": {"type": "string"}},
            "stop_conditions": {"type": "array", "items": {"type": "string"}},
        },
    },
    "coverage_review": {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schema",
            "round_no",
            "coverage_state",
            "covered_facets",
            "missing_facets",
            "source_failures",
            "quality_notes",
            "should_continue",
            "recommended_next_sources",
            "recommended_next_queries",
        ],
        "properties": {
            "schema": {"type": "string"},
            "round_no": {"type": "number"},
            "coverage_state": {"type": "string"},
            "covered_facets": {"type": "array", "items": {"type": "string"}},
            "missing_facets": {"type": "array", "items": {"type": "string"}},
            "source_failures": {"type": "array", "items": {"type": "string"}},
            "quality_notes": {"type": "array", "items": {"type": "string"}},
            "should_continue": {"type": "boolean"},
            "recommended_next_sources": {"type": "array", "items": {"type": "string"}},
            "recommended_next_queries": {"type": "array", "items": {"type": "string"}},
        },
    },
    "stop_decision": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "round_no", "should_continue", "reason", "confidence", "next_action"],
        "properties": {
            "schema": {"type": "string"},
            "round_no": {"type": "number"},
            "should_continue": {"type": "boolean"},
            "reason": {"type": "string"},
            "confidence": {"type": "string"},
            "next_action": {"type": "string"},
        },
    },
    "candidate_review": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "reviews"],
        "properties": {
            "schema": {"type": "string"},
            "reviews": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["candidate_id", "score", "reason", "risks", "recommended_use"],
                    "properties": {
                        "candidate_id": {"type": "string"},
                        "score": {"type": "number"},
                        "reason": {"type": "string"},
                        "risks": {"type": "array", "items": {"type": "string"}},
                        "recommended_use": {"type": "string"},
                    },
                },
            },
        },
    },
    "candidate_localization_review": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "reviews"],
        "properties": {
            "schema": {"type": "string"},
            "reviews": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": [
                        "candidate_id",
                        "chinese_web_access",
                        "documentation_language",
                        "domestic_platform_presence",
                        "availability_summary",
                        "risk_level",
                        "recommendation",
                        "reason",
                        "evidence_refs",
                    ],
                    "properties": {
                        "candidate_id": {"type": "string"},
                        "chinese_web_access": {"type": "string"},
                        "documentation_language": {"type": "array", "items": {"type": "string"}},
                        "domestic_platform_presence": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["gitee", "official_zh_docs", "cn_blog_evidence", "package_mirror"],
                            "properties": {
                                "gitee": {"type": "boolean"},
                                "official_zh_docs": {"type": "boolean"},
                                "cn_blog_evidence": {"type": "boolean"},
                                "package_mirror": {"type": "string"},
                            },
                        },
                        "availability_summary": {"type": "string"},
                        "risk_level": {"type": "string"},
                        "recommendation": {"type": "string"},
                        "reason": {"type": "string"},
                        "evidence_refs": {"type": "array", "items": {"type": "string"}},
                    },
                },
            },
        },
    },
    "next_options": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "current_state", "step_output", "next_options"],
        "properties": {
            "schema": {"type": "string"},
            "current_state": {
                "type": "object",
                "additionalProperties": False,
                "required": ["run_id", "stage", "completion_quality", "summary", "weak_points"],
                "properties": {
                    "run_id": {"type": "string"},
                    "stage": {"type": "string"},
                    "completion_quality": {"type": "string"},
                    "summary": {"type": "string"},
                    "weak_points": {"type": "array", "items": {"type": "string"}},
                },
            },
            "step_output": {
                "type": "object",
                "additionalProperties": False,
                "required": ["report_ref", "source_status_ref", "candidate_refs"],
                "properties": {
                    "report_ref": {"type": "string"},
                    "source_status_ref": {"type": "string"},
                    "candidate_refs": {"type": "array", "items": {"type": "string"}},
                    "research_contract_ref": {"type": "string"},
                    "branch_report_refs": {"type": "array", "items": {"type": "string"}},
                    "decision_matrix_ref": {"type": "string"},
                    "selected_branch_ref": {"type": "string"},
                },
            },
            "next_options": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["id", "label", "intent_examples", "command", "requires_model", "requires_approval"],
                    "properties": {
                        "id": {"type": "string"},
                        "label": {"type": "string"},
                        "intent_examples": {"type": "array", "items": {"type": "string"}},
                        "command": {"type": "string"},
                        "requires_model": {"type": "boolean"},
                        "requires_approval": {"type": "boolean"},
                    },
                },
            },
        },
    },
    "continue_intent_route": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "route", "confidence", "reason", "scope", "updated_idea", "requires_approval", "next_prompt"],
        "properties": {
            "schema": {"type": "string"},
            "route": {"type": "string"},
            "confidence": {"type": "number"},
            "reason": {"type": "string"},
            "scope": {"type": "string"},
            "updated_idea": {"type": "string"},
            "requires_approval": {"type": "boolean"},
            "next_prompt": {"type": "string"},
        },
    },
    "updated_intent": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "updated_idea", "reason", "constraints", "next_options"],
        "properties": {
            "schema": {"type": "string"},
            "updated_idea": {"type": "string"},
            "reason": {"type": "string"},
            "constraints": {"type": "array", "items": {"type": "string"}},
            "next_options": {"type": "array", "items": {"type": "string"}},
        },
    },
    "chunked_research_plan": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "chunks", "execution_note"],
        "properties": {
            "schema": {"type": "string"},
            "execution_note": {"type": "string"},
            "chunks": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["id", "label", "scope", "reason", "status"],
                    "properties": {
                        "id": {"type": "string"},
                        "label": {"type": "string"},
                        "scope": {"type": "string"},
                        "reason": {"type": "string"},
                        "status": {"type": "string"},
                    },
                },
            },
        },
    },
    "risk_analysis": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "risks", "blocked_actions", "approval_required"],
        "properties": {
            "schema": {"type": "string"},
            "risks": {"type": "array", "items": {"type": "string"}},
            "blocked_actions": {"type": "array", "items": {"type": "string"}},
            "approval_required": {"type": "boolean"},
        },
    },
    "failure_recovery_guidance": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "summary", "probable_root_cause", "safe_next_attempts", "manual_user_actions", "stop_conditions", "recommended_actions"],
        "properties": {
            "schema": {"type": "string"},
            "summary": {"type": "string"},
            "probable_root_cause": {"type": "string"},
            "safe_next_attempts": {"type": "array", "items": {"type": "string"}},
            "manual_user_actions": {"type": "array", "items": {"type": "string"}},
            "stop_conditions": {"type": "array", "items": {"type": "string"}},
            "recommended_actions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["action_id", "rationale"],
                    "properties": {
                        "action_id": {"type": "string"},
                        "rationale": {"type": "string"},
                        "requires_escalation": {"type": "boolean"},
                        "risk_summary": {"type": "string"},
                        "command": {"type": "string"},
                        "service": {"type": "string"},
                        "paths": {"type": "array", "items": {"type": "string"}},
                    },
                },
            },
        },
    },
    "github_auth_failure_guidance": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "summary", "probable_root_cause", "safe_next_attempts", "manual_user_actions", "stop_conditions", "recommended_actions"],
        "properties": {
            "schema": {"type": "string"},
            "summary": {"type": "string"},
            "probable_root_cause": {"type": "string"},
            "safe_next_attempts": {"type": "array", "items": {"type": "string"}},
            "manual_user_actions": {"type": "array", "items": {"type": "string"}},
            "stop_conditions": {"type": "array", "items": {"type": "string"}},
            "recommended_actions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["action_id", "rationale"],
                    "properties": {
                        "action_id": {"type": "string"},
                        "rationale": {"type": "string"},
                        "requires_escalation": {"type": "boolean"},
                        "risk_summary": {"type": "string"},
                        "command": {"type": "string"},
                        "service": {"type": "string"},
                        "paths": {"type": "array", "items": {"type": "string"}},
                    },
                },
            },
        },
    },
    "final_report": {
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "summary", "findings", "next_action_plan"],
        "properties": {
            "schema": {"type": "string"},
            "summary": {"type": "string"},
            "findings": {"type": "array", "items": {"type": "string"}},
            "next_action_plan": {"type": "array", "items": {"type": "string"}},
        },
    },
}
